/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ilucky_test_jdk_native2_HelloJNI */

#ifndef _Included_com_ilucky_test_jdk_native2_HelloJNI
#define _Included_com_ilucky_test_jdk_native2_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ilucky_test_jdk_native2_HelloJNI
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ilucky_test_jdk_native2_HelloJNI_printHello
  (JNIEnv *, jobject);

/*
 * Class:     com_ilucky_test_jdk_native2_HelloJNI
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ilucky_test_jdk_native2_HelloJNI_printString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
